### ISSUE TITLE
Was ist der Windows-Key ?

### ISSUE THREAD

**Issue by xstable** [tschulte/ergodox-firmware#3]
Ist in der Firmware der Windows-Key schon vorhanden?
LGUI und RGUI sind ja das Kontextmenü. 
Die Windows-Key-Taste habe ich noch nirgendwo gefunden.

**Comment by tschulte** [comment]
Nein, KEYBOARD__Application ist das Kontextmenü, KEYBOARD__LeftGUI und KEYBOARD__RightGUI sind die linke und rechte Windows-Taste.
